name: vpn
description: A Flutter VPN client for Proton VPN free tier.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  json_annotation: ^4.12.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  wireguard_flutter: ^0.1.3
  system_tray: ^2.0.0
  flutter_local_notifications: ^21.0.0
  http: ^1.1.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.0+1
  connectivity_plus: ^4.0.2
  pointycastle: ^3.7.3
  convert: ^3.1.1
  crypto: ^3.0.3
  cryptography: ^2.9.0
  bcrypt: ^1.2.0

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/flags/